POST http://localhost:8002/auth/register/
Content-Type: application/json

{
    "username": "test",
    "email": "test@example.com",
    "password": "admin@123"
}

###
POST http://localhost:8002/api/properties/
Content-Type: application/json

{
    "title": "title ok",
    "snippet": "ok this is snippet",
    "availability": "yes",
    "address": "Hariyana",
    "country": "PK",
    "price": "9090",
    "description": "tdesc",
}



###
POST http://localhost:8002/auth/token/
Content-Type: application/json

{
    "username": "test",
    "password": "admin@123"
}


###
GET http://localhost:8002/api/properties/


###
GET http://localhost:8002/dashboard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM2MDk2MTYyLCJpYXQiOjE3MzYwOTU4NjIsImp0aSI6IjE2MzNiMTAzNTg0MDRhNTNiNDdmMDI4M2Y4YTUxZDc3IiwidXNlcl9pZCI6Mn0.2OSgAjeOepKvWrRe1pDhpaveGjAsZXDdiRMPzaKaVgw

